# ------------------------------------------------------------------------------------------------------------------
# Rosalind problems:
# 1) Count the number of A, C, G, T present in the given nucleotide sequence
#-------------------------------------------------------------------------------------------------------------------

count_val = {'A':0, 'T':0, 'G':0, 'C':0}
input_seq = "CGCCCAGCGGCTATATCAGCTGTAACTTGGCGACAGATCCGAGACGAACCTTTCATCGAACTATGCATCCAGGCCGTAACGATATCGCCGGCAGCCCCACATGGCATTCGATGGAGTCCTTCTACTAAAGGGCCCGCCAGCGGACGGTTCCACCTTTTTGCCCTAATGCCCCTGTGGAGGCGTCGGTTAGTGAAGACATGGAATCCGCTCCACTGGCATTTCTTCTGGTTCTGACGATTGTGCATATGAGGGTACGTGCGCAACGCATACTGGGAACAATCTTAGCGATAGGGGATGTTCCAGGACACCAGAACGCAAGGTGTCACGTAGCCAAAAAGATGCGCCTTATGTCCTCAGATTCCCACGCATTGGCTTTGGATACTTTCGTACGGTACGTGTTTACACTGTTTCCCCGGCGTGTTCTAACGACGTCTTGTAGAGTCCCTTGAAATTGAAGTACCAGTTGAGCGGTGGTGATACCGTAAAAGTTACAGGAAGAAGCAACATTTAGCAAGGCGTGTTGTCTAGGACGCACATTGTTAAGGATGTAATCAGCTTCCATCAAAATGGGATAACGCCCAGACAGCATAAATTAGGCACCAACAAAAGCGAGTATCCAGTCGTGACACTGAGCCGGTATTCGGGGGTGAGCTCTGTACCGAATAAAATCTTAACGGAAGAACTGTTAATTTGCGTAGTTCTGCGACGCAAACCGGCTTAGCAGAGAGATGTGAGGTTACAATTGATTGAACCACCTCACAGTCAAATATTGCACGCTGACAACCAACATTCATTCCCGACACCGAGCTAATTGCCGCGTCCCGAGCAATTTGACATCTGAGGCCACTATAAGCACAGTGTTGCGACTATATTCTGGCGGGACCATGAGCCTGACAGTTGACGTGAGTACCTGTCGGATCACGCCGGTCTGTGGAGTCCTAGGTAGCTCCCTGACCGAGGGGGCTTAGCATTGC"

for nuc in input_seq:
    count_val[nuc] += 1

print count_val