# ------------------------------------------------------------------------------------------------------------------
# Rosalind problems:
# 2) Transcribe the given DNA sequence to RNA sequence
#-------------------------------------------------------------------------------------------------------------------
from Bio.Seq import Seq

input_seq = Seq("ACTAAGTTCCATCCCTCCGAATATGCACTCGGAACCAGTCACTAGCAAGATCTACACCGAACGATTCTCGAGCATGCACCTACAAATGAATATGAAGCGGTCCGCACCTTCCAACAACTCCAGTTAGAGCAGTCAAAGTAAGAAAGTAGCACACGCGTTGTAGATTCTGTAAATATGCTGTTCATGTCCCATGAACGCATCAGCGTGCGGTTTCATATTAATCGGAGGAAGCCAAGAGATAGTACCTGACGATTGACTCACTTCACTGCATACACAGGGTCAGCCCTTCGAGTTCCTTGGACAGCATGGGTGAGCCCAGTGTCTAATCCCTTTATCTACCAAGGTCGGCCTTCACGCGTGCTCTGCAAGTTTAAATACGTGCCGGTCCTGAAGCATACTGTCGTATCACACCGGTGAAGACACGCGCCGTCATTGACACGGCCATAAGTGGAATTTTCCGACTAAGACACGGCAGGTCTACCACCCCCAGGAGCCCCTCCTAACGATTACCTCCCTCGTACACACCGCGCGCACTCGTAATGGGCCAGCTTGGCTTTCCAATCATCTTCACCAATCCGGCGTCCATTCAGCAAGTTTCTAACTGCCCTGCGTCGGCGGATGTGGAGGTAAGAGGGGAGTCAGTGGAATACGACAGGGGTACAAGCAAACTAGTAGGTGGTTCTTGATTTGGATTACGATCCCGTTCTTATTGTGGTAGGTCATCACTCTTGTCTTTCATGCGGAGGGACGTACGCAGAGGCTAGATACTCAAGTGACATGTCCCCGCAGCGTGGTGTCGCTGTCCATTAGGATGCCTAACATGCAATACCCGAGGAGCTACTTTCCTCCACCCAATGACCTACATACCTGACGTGATAAGAAGCCCCAACCACCAACTGTTGGATCGCTAACTTTCCCTCGCTCCAGAGCTATTGTAGGTCTCTAGTGCCTCGTGTAGGATGGTGTGCCGGCACC")
print input_seq.transcribe()
