# ------------------------------------------------------------------------------------------------------------------
# Rosalind problems:
# 3) Find the reverse complement of the given DNA sequence
#-------------------------------------------------------------------------------------------------------------------
from Bio.Seq import Seq

input_seq = Seq("GTGTTCGAAGATCGGACCTTCTCAACTGAAGAACCTGAGACAGATGACGAGCTGTGTGTTTTCTCAAAATCGTGAGAAAATTAAAATAGATCGCAGATTAGTGGACCAACCTCTTCTACGACGTTGACGCTGGGGCTAAGTGGCGATAGTAATTGTCACTAGCAATGCGTGCTAAGAGATTGGGGGGCACCTTGCCAGGCGAGTATAGGCTGTAAATTTTAAGATATGGTTCGGGCGCCGTCGGGTTTTCTTCAGCCTGCGCAACCCTTCGTGATATAAACGGAAAAGCCGGTGCTTTTAGAGTAGTGTAAAGGCGTTACAGTTCATGTGTGAAACCCTTAGCAATATCGGGCGGAGGCCCTCGTGGCACTTCCCAGTGCTACGGCACAACATATTTCGAAGCTGCAACTTGTTAGGCAAACAATAATGGTCCGCATAGGGGATTAATCTTGCGGCTCAGATAGTCTATTCCGTCCCACGGATCGCCACCCCGATTGCTATGCGCCCCACAGCATTATCTTGCTGGCAATGCTGAAAGACGTAAGACATGTGGTCCTTCGGTGGGTTACCGAAGCCTAGGTAAAGATGATCGGCTGACCCAAAAGAGCCGACAAACCTTATTGATATTGAAATTGCGCCCTCCGGTGCAACGATGGTCCATTCCCGTAAATGTGTGGGAGGCATCAGGATTACGTCGGCGCTCGTAGGCGAATACTTCACCCCAAGAGAAGGTCCCAGGCGGGTACACTCTGCAATATCACTGACTTGACATCACCACATAGTGCGAATTATTAGACAATGGGTGAAGCTCCTAAATCAAAGTTCTGAGGAGCGCAGCCCTGCTGGCCAGCTCATGGATGCTCGGGACGTTCCGGTTGGTTGGGCGGGCAGGTGTTTCGGGCTTATTTACTGACGTCCCGAACGGAACGGAGCAGGCCAATTCGGACCAGCGAGGCAATATACTATGGCTGTCATAAGTTCAGCTCAGAGACCGTA")

print input_seq.reverse_complement()